routes/web.php
<?php

use App\Http\Controllers\Admin\BlogCategoryController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CareerController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ServiceCategoryController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Frontend\CareerApplyController;
use App\Http\Controllers\Frontend\CourseBookingSiteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('backend.system.welcome');
//});
Route::get('course-status', [CourseController::class, 'changeStatus']);
Route::get('partner-status', [PartnerController::class, 'changeStatus']);
Route::get('slider-status', [SliderController::class, 'changeStatus']);
Route::get('blog-status', [BlogController::class, 'changeStatus']);
Route::get('career-status', [CareerController::class, 'changeStatus']);
Route::get('career-apply-status', [CareerApplyController::class, 'changeStatus']);
Route::get('faqs-status', [FaqsController::class, 'changeStatus']);
Route::get('menu-status', [MenuController::class, 'changeStatus']);
Route::get('blogcategory-status', [BlogCategoryController::class, 'changeStatus']);
Route::get('servicecategory-status', [ServiceCategoryController::class, 'changeStatus']);
Route::get('testimonial-status', [TestimonialController::class, 'changeStatus']);


// Route::get('profile', ['as' => 'profile', 'uses' => 'HomeController@profile']);
// Route::get('email', [HomeController::class, 'sendMail']);

Route::get('language/{lang}', function ($lang) {
    session()->put('locale', $lang);
    return redirect()->back();
})->name('change.locale');


// Route::resources('career-apply', CareerApplyController::class);


Route::prefix('admin')->group(function () {
    Route::get('login', [AuthController::class, 'adminLoginIndex'])->name('admin.login.index');
    Route::post('login', [AuthController::class, 'login'])->name('admin.login');
    Route::post('logout', [AuthController::class, 'logout'])->name('admin.logout');
});
//Route::get('home', ['as' => 'home','uses' => 'HomeController@index']);
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin')->as('admin.')->group(function () {

        Route::resource('roles', Rolecontroller::class);
        Route::get('roles/delete/{id}', [RoleController::class, 'destroy'])->name('roles.delete');
        Route::resource('users', Usercontroller::class);
        Route::get('users/delete/{id}', [UserController::class, 'destroy'])->name('users.delete');
        Route::group(['namespace' => 'App\Http\Controllers\Admin'], function () {
            Route::get('board', ['as' => 'home', 'uses' => 'HomeController@index']);

            //email setting route
            Route::get('email-setting', ['as' => 'email-setting.index', 'uses' => "EmailSettingController@index"]);
            Route::post('email-setting', ['as' => 'email-setting.update', 'uses' => 'EmailSettingController@update']);
            Route::post('send-test-mail', ['as' => 'email-setting.sendMail', 'uses' => 'EmailSettingController@sendMail']);

            //course controller
            Route::get('course', ['as' => 'course.index', 'uses' => 'CourseController@index']);
            Route::get('course-create', ['as' => 'course.create', 'uses' => 'CourseController@create']);
            Route::post('course-store', ['as' => 'course.store', 'uses' => 'CourseController@store']);
            Route::get('course-edit/{id}', ['as' => 'course.edit', 'uses' => 'CourseController@edit']);
            Route::post('course-update/{id}', ['as' => 'course.update', 'uses' => 'CourseController@update']);
            Route::get('course-delete/{id}', ['as' => 'course.delete', 'uses' => 'CourseController@destroy']);

            //course detail controller router
            Route::group(['prefix' => 'course-detail'], function () {
                Route::get('', ['as' => 'course.detail.index', 'uses' => 'CourseDetailController@index']);
                Route::get('create', ['as' => 'course.detail.create', 'uses' => 'CourseDetailController@create']);
                Route::post('store', ['as' => 'course.detail.store', 'uses' => 'CourseDetailController@store']);
                Route::get('edit/{id}', ['as' => 'course.detail.edit', 'uses' => 'CourseDetailController@edit']);
                Route::post('update/{id}', ['as' => 'course.detail.update', 'uses' => 'CourseDetailController@update']);
                Route::get('delete/{id}', ['as' => 'course.detail.delete', 'uses' => 'CourseDetailController@destroy']);
            });


            //partner controller 
            Route::get('partner', ['as' => 'partner.index', 'uses' => 'PartnerController@index']);
            Route::get('partner-create', ['as' => 'partner.create', 'uses' => 'PartnerController@create']);
            Route::post('partner-store', ['as' => 'partner.store', 'uses' => 'PartnerController@store']);
            Route::get('partner-edit/{id}', ['as' => 'partner.edit', 'uses' => 'PartnerController@edit']);
            Route::post('partner-update/{id}', ['as' => 'partner.update', 'uses' => 'PartnerController@update']);
            Route::get('partner-delete/{id}', ['as' => 'partner.delete', 'uses' => 'PartnerController@destroy']);

            //course categogry
            Route::get('course-category', ['as' => 'course.category.index', 'uses' => 'CourseCategoryController@index']);
            Route::get('course-category-create', ['as' => 'course.category.create', 'uses' => 'CourseCategoryController@create']);
            Route::post('course-category-store', ['as' => 'course.category.store', 'uses' => 'CourseCategoryController@store']);
            Route::post('course-category-update/{id}', ['as' => 'course.category.update', 'uses' => 'CourseCategoryController@update']);
            Route::get('course-category-delete/{id}', ['as' => 'course.category.delete', 'uses' => 'CourseCategoryController@destroy']);

            //slider
            Route::get('slider', ['as' => 'slider.index', 'uses' => 'SliderController@index']);
            Route::get('slider-create', ['as' => 'slider.create', 'uses' => 'SliderController@create']);
            Route::post('slider-store', ['as' => 'slider.store', 'uses' => 'SliderController@store']);
            Route::get('slider-edit/{id}', ['as' => 'slider.edit', 'uses' => 'SliderController@edit']);
            Route::post('slider-update/{id}', ['as' => 'slider.update', 'uses' => 'SliderController@update']);
            Route::get('slider-delete/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@destroy']);


            //Blog category route
            Route::get('blog-category', ['as' => 'blog.category.index', 'uses' => 'BlogCategoryController@index']);
            Route::get('blog-category-create', ['as' => 'blog.category.create', 'uses' => 'BlogCategoryController@create']);
            Route::post('blog-category-store', ['as' => 'blog.category.store', 'uses' => 'BlogCategoryController@store']);
            Route::post('blog-category-update/{id}', ['as' => 'blog.category.update', 'uses' => 'BlogCategoryController@update']);
            Route::get('blog-category-delete/{id}', ['as' => 'blog.category.delete', 'uses' => 'BlogCategoryController@destroy']);

            //blog route
            Route::get('blog', ['as' => 'blog.index', 'uses' => 'BlogController@index']);
            Route::get('blog-create', ['as' => 'blog.create', 'uses' => 'BlogController@create']);
            Route::post('blog-store', ['as' => 'blog.store', 'uses' => 'BlogController@store']);
            Route::get('blog-edit/{id}', ['as' => 'blog.edit', 'uses' => 'BlogController@edit']);
            Route::post('blog-update/{id}', ['as' => 'blog.update', 'uses' => 'BlogController@update']);
            Route::get('blog-delete/{id}', ['as' => 'blog.delete', 'uses' => 'BlogController@destroy']);

            //Career route
            Route::get('career', ['as' => 'career.index', 'uses' => 'CareerController@index']);
            Route::get('career-create', ['as' => 'career.create', 'uses' => 'CareerController@create']);
            Route::post('career-store', ['as' => 'career.store', 'uses' => 'CareerController@store']);
            Route::get('career-edit/{id}', ['as' => 'career.edit', 'uses' => 'CareerController@edit']);
            Route::post('career-update/{id}', ['as' => 'career.update', 'uses' => 'CareerController@update']);
            Route::get('career-delete/{id}', ['as' => 'career.delete', 'uses' => 'CareerController@destroy']);

            // faqs route 
            Route::get('faqs', ['as' => 'faqs.index', 'uses' => 'FaqsController@index']);
            Route::get('faqs-create', ['as' => 'faqs.create', 'uses' => 'FaqsController@create']);
            Route::post('faqs-store', ['as' => 'faqs.store', 'uses' => 'FaqsController@store']);
            Route::get('faqs-edit/{id}', ['as' => 'faqs.edit', 'uses' => 'FaqsController@edit']);
            Route::post('faqs-update/{id}', ['as' => 'faqs.update', 'uses' => 'FaqsController@update']);
            Route::get('faqs-delete/{id}', ['as' => 'faqs.delete', 'uses' => 'FaqsController@destroy']);


            //menu web route

app/Models/Slider.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Slider extends Model
{
    use HasFactory;
    protected $fillable = [
        'title',
        'sub_title',
        'short_detail',
        'image',
        'url',
        'course_id'

    ];

    public function Course()
    {
        return $this->belongsTo(Course::class, 'course_id');
    }
}

app/Http/Controllers/Admin/SliderController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Course;
use App\Models\CourseCategory;
use App\Models\Slider;
use Illuminate\Http\Request;

class SliderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page_title = "Slider List";
        $page_description = "List Slider";
        $search = $request->search;
        $data = Slider::when($search, function ($q) use ($search) {
            $q->where('title', 'LIKE', '%' . $search . '%');
        })->orderBy('id', 'desc')->paginate(5);
        return view('backend.system.slider.index', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = "Slider Create";
        $page_description = "Slider Create";
        $course = Course::select('id', 'title')->get();
        return  view('backend.system.slider.create', compact('page_title', 'page_description', 'course'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'sub_title' => 'required',
            'short_detail' => 'required',
            'url' => 'required',
            'image' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'course_id' => 'required'
        ]);

        $attribute = $request->all();
        if ($image = $request->file('image')) {
            $destinationPath = 'uploads/slider/images';
            $Image = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $Image);
            $attribute['image'] = "$Image";
        }
        Slider::create($attribute);
        return redirect()->route('admin.slider.index')->with('success', 'Slider created Successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $page_title = "Slider Edit";
        $page_description = "Slider Edit";
        $course = Course::select('id', 'title')->get();
        $slider = Slider::find($id);
        return view('backend.system.slider.edit', compact('page_title', 'page_description', 'slider', 'course'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $slider = Slider::find($id);
        $request->validate([
            'title' => 'required',
            'sub_title' => 'required',
            'short_detail' => 'required',
            'url' => 'required',
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'course_id' => 'required'
        ]);
        $attribute = $request->all();
        $imagePath = 'uploads/slider/images' . $slider->image;
        if (file_exists($imagePath)) {
            unlink($imagePath);
        }
        if ($image = $request->file('image')) {
            $destinationPath = 'uploads/slider/images';
            $Image = date('YmdHis') . "." . $image->getClientOriginalExtension();
            $image->move($destinationPath, $Image);
            $attribute['image'] = $Image ?? $slider->image;
        }
        $slider->update($attribute);
        return redirect()->route('admin.slider.index')->with('success', 'Slider updated Successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $slider = Slider::find($id);
        $imagePath = 'uploads/slider/images' . $slider->image;
        if (file_exists($imagePath)) {
            unlink($imagePath);
        }
        $slider->delete();
        return redirect()->back()->with('success', 'Slider deleted successfully');
    }
    public function changeStatus(Request $request)
    {
        $slider = Slider::find($request->slider_id);
        $slider->status = $request->status;
        $slider->save();
        // return response()->json(['success' => 'Status change successfully.']);
    }
}

resources/views/backend/system/slider/create.blade.php
@extends('backend.system.layouts.master')
@section('content')
    <style>
        .file-drop-area {
            position: relative;
            padding: 0.4rem 0rem;
            height: 245px;
            max-height: 250px;
        }

        .file-drop-area .file-drop-preview {
            max-width: 6rem;
        }

    </style>
    {{-- @dd($category) --}}
    <div class="content-header">
        <div class="container">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">New Slider</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">Dashboard</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#">
                                User </a></li>
                        <li class="breadcrumb-item active">New Slider</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div>
    </div>

    <!-- /.content-header -->
    <section class="container">
        <section class="content">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-body">
                            <form method="POST" enctype="multipart/form-data" action="{{ route('admin.slider.store') }}">
                                @csrf
                                <div class="row">
                                    <div class="form-group col-6">
                                        <label for="title">Title</label>
                                        <input type="text" name="title" class="form-control" id="title"
                                            placeholder="Enter title" value="{{ old('title') }}">
                                        @if ($errors->has('title'))
                                            <p style="color: red">
                                                {{ $errors->first('title') }}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="form-group col-6">
                                        <label for="title">Sub Title</label>
                                        <input type="text" name="sub_title" class="form-control" id="sub_title"
                                            placeholder="Enter meta title" value="{{ old('sub_title') }}">
                                        @if ($errors->has('sub_title'))
                                            <p style="color: red">
                                                {{ $errors->first('sub_title') }}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="form-group col-6 ">
                                        <label for="role">Choose Course </label>
                                        <select class="form-control select2" name="course_id" id="category_id">
                                            @foreach ($course as $type)
                                                <option value="{{ $type->id }}">{{ $type->title }}</option>
                                            @endforeach
                                        </select>
                                        @if ($errors->has('category_id'))
                                            <p style="color: red">
                                                {{ $errors->first('category_id') }}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="form-group col-6">
                                        <label for="designation">Url</label>
                                        <input type="url" name="url" class="form-control" id="url"
                                            placeholder="Enter description" value="{{ old('url') }}">
                                        @if ($errors->has('url'))
                                            <p style="color: red">
                                                {{ $errors->first('url') }}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="form-group col-6">
                                        <label for="designation">Image</label>
                                        <input type="file" name="image" class="form-control" id="image" placeholder=""
                                            required>
                                        @if ($errors->has('url'))
                                            <p style="color: red">
                                                {{ $errors->first('url') }}
                                            </p>
                                        @endif
                                    </div>
                                    <div class="form-group col-6">
                                        <label for="title">Short Detail</label>
                                        {{-- <input type="text" name="short_detail" class="form-control" id=""
                                            placeholder="Enter Og meta title" required> --}}
                                        <textarea name="short_detail" id="summernote" cols="30" rows="10"
                                            value="{{ old('short_detail') }}"></textarea>
                                        @if ($errors->has('short_detail'))
                                            <p style="color: red">
                                                {{ $errors->first('short_detail') }}
                                            </p>
                                        @endif
                                    </div>
                                </div>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <button class="btn btn-info me-md-2" type="submit">Create</button>
                                    <a class="btn btn-info" type="button"
                                        href="{{ route('admin.slider.index') }}">Cancel</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </section>
    </section>
    <!-- /.content-wrapper -->
@endsection

resources/views/backend/system/slider/index.blade.php
@extends('backend.system.layouts.master')
@section('content')
    <section class="content-header">

        <div class="container">
            <div style="z-index: 200; position:absolute; top:90px; right:30px;">
                @include('flash-message')
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    <h1 class="m-0 text-dark">
                        {!! $page_title ?? 'Page Title' !!}
                        <small style="color: grey; font-size: xx-small">{!! $page_description ?? 'Page description' !!}</small>
                    </h1>
                </div><!-- /.col -->
                <div class="col-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">{{ __('vehicle_type.dashboard') }}</a>
                        </li>
                        <li class="breadcrumb-item active">{!! $page_title ?? 'Page Title' !!}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div>

    </section>

    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card border-info">
                        <div class="card-header border-info">
                            <div class='row'>
                                <div class="col-sm-12 col-md-6 mb-1 d-inline-flex">

                                    <a class="d-flex align-item-center mt-1 btn-outline-info rounded-pill btn-icon" href="#"
                                        title="Refresh">
                                        <em class="fas fa-redo fa-1x"></em>
                                    </a>
                                    <form action="#" class='d-flex align-items-center search' style="margin-left: 20px;"
                                        method="GET">
                                        <div>
                                            <input type="text" value="" placeholder="Search" class="form-control"
                                                name="search" required />
                                        </div>
                                        <button class="btn btn-info btn-sm btn-shadow me-1"
                                            type="submit">{{ __('vehicle_type.search') }}</button>
                                    </form>
                                </div>
                                <div class="col-sm-12 col-md-6">

                                    <a href="{{ route('admin.slider.create') }}" class="btn btn-info btn-sm float-right">
                                        <em data-feather="plus"></em>New Slider</a>
                                </div>

                            </div>
                        </div>
                        <div class="card-body table-responsive">
                            <table id="example2" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Sno</th>
                                        <th scope="col">Title</th>
                                        <th scope="col">Sub Title</th>
                                        <th scope="col">Short Detail</th>
                                        <th scope="col">Image</th>
                                        <th scope="col">Url</th>
                                        <th scope="col">Actions</th>
                                        <th scope="col">Status</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $k => $v)
                                        <tr>
                                            <td class="align-middle">{{ ++$k }}</td>
                                            <td class="align-middle">{{ $v->title }}</td>
                                            <td class="align-middle">{{ $v->sub_title }}</td>
                                            <td class="align-middle">{!! $v->short_detail !!}</td>
                                            <td class="align-middle"><img
                                                    src="{{ asset('uploads/slider/images/' . $v->image) }}" alt="image"
                                                    style="height: 40px; width:40px;"></td>
                                            <td class="align-middle">{{ $v->url }}</td>

                                            <td>
                                                <a href="{{ route('admin.slider.edit', $v->id) }}"
                                                    class="btn btn-outline-accent btn-icon">
                                                    <i class="ci-edit"></i>
                                                </a>

                                                &nbsp;
                                                <a href="{{ route('admin.slider.delete', $v->id) }}"
                                                    class="btn btn-outline-danger btn-icon"
                                                    onclick="return confirm('Are you sure you want to delete this item?')">
                                                    <i class="ci-trash"></i>
                                                </a>
                                            </td>
                                            <td>
                                                <div class="form-check form-switch ml-2 mt-2">
                                                    <input type="checkbox" class="form-check-input" id="customSwitch2"
                                                        data-id="{{ $v->id }}" {{ $v->status ? 'checked' : '' }}>
                                                </div>
                                            </td>
                                        </tr>
                                        @include('modal.course.course-detail')
                                    @endforeach
                                </tbody>
                            </table>
                            <nav class="d-flex justify-content-around pt-3" aria-label="Page navigation">
                                {{ $data->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!-- /.row -->

    <script>
        $(function() {
            $('.form-check-input').change(function() {
                var status = $(this).prop('checked') == true ? 1 : 0;
                var slider_id = $(this).data('id');
                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: '/slider-status',
                    data: {
                        'status': status,
                        'slider_id': slider_id
                    },
                    // success: function(data) {
                    //     console.log(data.success)

                    // }
                })
            })
        });
    </script>

@endsection


<!-- Optional bottom section for modals etc... -->
@section('body_bottom')
    <!-- DataTables -->
@endsection

@section('cdn')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/css/bootstrap-toggle.css"
        integrity="sha512-9tISBnhZjiw7MV4a1gbemtB9tmPcoJ7ahj8QWIc0daBCdvlKjEA48oLlo6zALYm3037tPYYulT0YQyJIJJoyMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"
        integrity="sha512-F636MAkMAhtTplahL9F6KmTfxTmYcAcjcCkyu0f0voT3N/6vzAuJ4Num55a0gEJ+hRLHhdz3vDvZpf6kqgEa5w=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@endsection