routes/web.php
<?php

use App\Http\Controllers\Admin\BlogCategoryController;
use App\Http\Controllers\Admin\CourseController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\PartnerController;
use App\Http\Controllers\Admin\SliderController;
use App\Http\Controllers\Admin\BlogController;
use App\Http\Controllers\Admin\CareerController;
use App\Http\Controllers\Admin\FaqsController;
use App\Http\Controllers\Admin\MenuController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ServiceCategoryController;
use App\Http\Controllers\Admin\TestimonialController;
use App\Http\Controllers\Frontend\CareerApplyController;
use App\Http\Controllers\Frontend\CourseBookingSiteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('backend.system.welcome');
//});
Route::get('course-status', [CourseController::class, 'changeStatus']);
Route::get('partner-status', [PartnerController::class, 'changeStatus']);
Route::get('slider-status', [SliderController::class, 'changeStatus']);
Route::get('blog-status', [BlogController::class, 'changeStatus']);
Route::get('career-status', [CareerController::class, 'changeStatus']);
Route::get('career-apply-status', [CareerApplyController::class, 'changeStatus']);
Route::get('faqs-status', [FaqsController::class, 'changeStatus']);
Route::get('menu-status', [MenuController::class, 'changeStatus']);
Route::get('blogcategory-status', [BlogCategoryController::class, 'changeStatus']);
Route::get('servicecategory-status', [ServiceCategoryController::class, 'changeStatus']);
Route::get('testimonial-status', [TestimonialController::class, 'changeStatus']);


// Route::get('profile', ['as' => 'profile', 'uses' => 'HomeController@profile']);
// Route::get('email', [HomeController::class, 'sendMail']);

Route::get('language/{lang}', function ($lang) {
    session()->put('locale', $lang);
    return redirect()->back();
})->name('change.locale');


// Route::resources('career-apply', CareerApplyController::class);


Route::prefix('admin')->group(function () {
    Route::get('login', [AuthController::class, 'adminLoginIndex'])->name('admin.login.index');
    Route::post('login', [AuthController::class, 'login'])->name('admin.login');
    Route::post('logout', [AuthController::class, 'logout'])->name('admin.logout');
});
//Route::get('home', ['as' => 'home','uses' => 'HomeController@index']);
Route::group(['middleware' => ['auth']], function () {
    Route::prefix('admin')->as('admin.')->group(function () {

        Route::resource('roles', Rolecontroller::class);
        Route::get('roles/delete/{id}', [RoleController::class, 'destroy'])->name('roles.delete');
        Route::resource('users', Usercontroller::class);
        Route::get('users/delete/{id}', [UserController::class, 'destroy'])->name('users.delete');
        Route::group(['namespace' => 'App\Http\Controllers\Admin'], function () {
            Route::get('board', ['as' => 'home', 'uses' => 'HomeController@index']);

            //email setting route
            Route::get('email-setting', ['as' => 'email-setting.index', 'uses' => "EmailSettingController@index"]);
            Route::post('email-setting', ['as' => 'email-setting.update', 'uses' => 'EmailSettingController@update']);
            Route::post('send-test-mail', ['as' => 'email-setting.sendMail', 'uses' => 'EmailSettingController@sendMail']);

            //course controller
            Route::get('course', ['as' => 'course.index', 'uses' => 'CourseController@index']);
            Route::get('course-create', ['as' => 'course.create', 'uses' => 'CourseController@create']);
            Route::post('course-store', ['as' => 'course.store', 'uses' => 'CourseController@store']);
            Route::get('course-edit/{id}', ['as' => 'course.edit', 'uses' => 'CourseController@edit']);
            Route::post('course-update/{id}', ['as' => 'course.update', 'uses' => 'CourseController@update']);
            Route::get('course-delete/{id}', ['as' => 'course.delete', 'uses' => 'CourseController@destroy']);

            //course detail controller router
            Route::group(['prefix' => 'course-detail'], function () {
                Route::get('', ['as' => 'course.detail.index', 'uses' => 'CourseDetailController@index']);
                Route::get('create', ['as' => 'course.detail.create', 'uses' => 'CourseDetailController@create']);
                Route::post('store', ['as' => 'course.detail.store', 'uses' => 'CourseDetailController@store']);
                Route::get('edit/{id}', ['as' => 'course.detail.edit', 'uses' => 'CourseDetailController@edit']);
                Route::post('update/{id}', ['as' => 'course.detail.update', 'uses' => 'CourseDetailController@update']);
                Route::get('delete/{id}', ['as' => 'course.detail.delete', 'uses' => 'CourseDetailController@destroy']);
            });


            //partner controller 
            Route::get('partner', ['as' => 'partner.index', 'uses' => 'PartnerController@index']);
            Route::get('partner-create', ['as' => 'partner.create', 'uses' => 'PartnerController@create']);
            Route::post('partner-store', ['as' => 'partner.store', 'uses' => 'PartnerController@store']);
            Route::get('partner-edit/{id}', ['as' => 'partner.edit', 'uses' => 'PartnerController@edit']);
            Route::post('partner-update/{id}', ['as' => 'partner.update', 'uses' => 'PartnerController@update']);
            Route::get('partner-delete/{id}', ['as' => 'partner.delete', 'uses' => 'PartnerController@destroy']);

            //course categogry
            Route::get('course-category', ['as' => 'course.category.index', 'uses' => 'CourseCategoryController@index']);
            Route::get('course-category-create', ['as' => 'course.category.create', 'uses' => 'CourseCategoryController@create']);
            Route::post('course-category-store', ['as' => 'course.category.store', 'uses' => 'CourseCategoryController@store']);
            Route::post('course-category-update/{id}', ['as' => 'course.category.update', 'uses' => 'CourseCategoryController@update']);
            Route::get('course-category-delete/{id}', ['as' => 'course.category.delete', 'uses' => 'CourseCategoryController@destroy']);

            //slider
            Route::get('slider', ['as' => 'slider.index', 'uses' => 'SliderController@index']);
            Route::get('slider-create', ['as' => 'slider.create', 'uses' => 'SliderController@create']);
            Route::post('slider-store', ['as' => 'slider.store', 'uses' => 'SliderController@store']);
            Route::get('slider-edit/{id}', ['as' => 'slider.edit', 'uses' => 'SliderController@edit']);
            Route::post('slider-update/{id}', ['as' => 'slider.update', 'uses' => 'SliderController@update']);
            Route::get('slider-delete/{id}', ['as' => 'slider.delete', 'uses' => 'SliderController@destroy']);


            //Blog category route
            Route::get('blog-category', ['as' => 'blog.category.index', 'uses' => 'BlogCategoryController@index']);
            Route::get('blog-category-create', ['as' => 'blog.category.create', 'uses' => 'BlogCategoryController@create']);
            Route::post('blog-category-store', ['as' => 'blog.category.store', 'uses' => 'BlogCategoryController@store']);
            Route::post('blog-category-update/{id}', ['as' => 'blog.category.update', 'uses' => 'BlogCategoryController@update']);
            Route::get('blog-category-delete/{id}', ['as' => 'blog.category.delete', 'uses' => 'BlogCategoryController@destroy']);

            //blog route
            Route::get('blog', ['as' => 'blog.index', 'uses' => 'BlogController@index']);
            Route::get('blog-create', ['as' => 'blog.create', 'uses' => 'BlogController@create']);
            Route::post('blog-store', ['as' => 'blog.store', 'uses' => 'BlogController@store']);
            Route::get('blog-edit/{id}', ['as' => 'blog.edit', 'uses' => 'BlogController@edit']);
            Route::post('blog-update/{id}', ['as' => 'blog.update', 'uses' => 'BlogController@update']);
            Route::get('blog-delete/{id}', ['as' => 'blog.delete', 'uses' => 'BlogController@destroy']);

            //Career route
            Route::get('career', ['as' => 'career.index', 'uses' => 'CareerController@index']);
            Route::get('career-create', ['as' => 'career.create', 'uses' => 'CareerController@create']);
            Route::post('career-store', ['as' => 'career.store', 'uses' => 'CareerController@store']);
            Route::get('career-edit/{id}', ['as' => 'career.edit', 'uses' => 'CareerController@edit']);
            Route::post('career-update/{id}', ['as' => 'career.update', 'uses' => 'CareerController@update']);
            Route::get('career-delete/{id}', ['as' => 'career.delete', 'uses' => 'CareerController@destroy']);

            // faqs route 
            Route::get('faqs', ['as' => 'faqs.index', 'uses' => 'FaqsController@index']);
            Route::get('faqs-create', ['as' => 'faqs.create', 'uses' => 'FaqsController@create']);
            Route::post('faqs-store', ['as' => 'faqs.store', 'uses' => 'FaqsController@store']);
            Route::get('faqs-edit/{id}', ['as' => 'faqs.edit', 'uses' => 'FaqsController@edit']);
            Route::post('faqs-update/{id}', ['as' => 'faqs.update', 'uses' => 'FaqsController@update']);
            Route::get('faqs-delete/{id}', ['as' => 'faqs.delete', 'uses' => 'FaqsController@destroy']);


            //menu web route

app/Models/CourseCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CourseCategory extends Model
{
    use HasFactory;
    protected $fillable = ['name'];
}

app/Http/Controllers/Admin/CourseCategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\CourseCategory;
use Facade\FlareClient\View;
use Illuminate\Http\Request;

class CourseCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request  $request)
    {
        $page_title = "Course Category";
        $page_description = "Course Category";
        $search = $request->search;
        $data = CourseCategory::when($search, function ($q) use ($search) {
            $q->where('name', 'LIKE', '%' . $search . '%');
        })->orderBy('id', 'desc')->paginate(5);
        return View('backend.system.course-category.index', compact('page_title', 'page_description', 'data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $page_title = "Course Category Create";
        $page_description = "Course Category Ceate";
        return view('backend.system.course-category.create', compact('page_title', 'page_description'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required'
        ]);
        CourseCategory::create($request->all());
        return redirect()->back()->with('success', 'Course Category created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $course_category = CourseCategory::find($id);
        $request->validate([
            'name' => 'required'
        ]);
        $course_category->update($request->all());
        return redirect()->back()->with('success', 'Course Category updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $course_category = CourseCategory::find($id);
        $course_category->delete();
        return redirect()->back()->with('success', 'Course Category deletedf successfully');
    }
}

app/Http/Controllers/Api/CourseCategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\CourseCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CourseCategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $CourseCategory = CourseCategory::all();
        return response()->json(['CourseCategory' => $CourseCategory], 201);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $input = $request->all();
        $validator = Validator::make(
            $input,
            [
                'name' => 'required'
            ]
        );
        if ($validator->fails()) {
            return $this->sendError('Validation Error', $validator->errors());
        }
        $CourseCategory = CourseCategory::create($input);
        return response()->json([
            'success' => true,
            'message' => 'Course Category Created successfully',
            'data' => $CourseCategory
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $CourseCategory = CourseCategory::find($id);
        if (is_null($CourseCategory)) {
            return $this->sendError('Category not found');
        }
        return response()->json([
            'success' => true,
            'message' => 'Category Shown successfully',
            'data' => $CourseCategory
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Category = CourseCategory::find($id);
        $input = $request->all();
        $validator = Validator::make(
            $input,
            [
                'name' => 'required'
            ]
        );
        if ($validator->fails()) {
            return $this->sendError('Validation Error', $validator->errors());
        }
        $Category->update($input);
        return response()->json([
            'success' => true,
            'message' => 'Course Category updated successfully',
            'data' => $Category
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $CourseCategory = CourseCategory::find($id)->delete();
        return response()->json(['success'=>true,
        'message'=>'Course category deleted successfully',
    'id'=>CourseCategory::find($id)]);
    }
}

resources/views/backend/system/course-category/index.blade.php
@extends('backend.system.layouts.master')
@section('content')
    <section class="content-header">
        <div class="container">
            <div  style="z-index: 200; position:absolute; top:90px; right:30px;">
                @include('flash-message')
            </div>
            <div class="row mb-2">
                <div class="col-6">
                    <h1 class="m-0 text-dark">
                        {!! $page_title ?? 'Page Title' !!}
                        <small style="color: grey; font-size: xx-small">{!! $page_description ?? 'Page description' !!}</small>
                    </h1>
                </div><!-- /.col -->
                <div class="col-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="/">{{ __('vehicle_type.dashboard') }}</a>
                        </li>
                        <li class="breadcrumb-item active">{!! $page_title ?? 'Page Title' !!}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div>

    </section>

    <section>
        <div class="container-fluid">
            <div class="row">
                <div class="col-12">
                    <div class="card border-info">
                        <div class="card-header border-info">
                            <div class='row'>
                                <div class="col-sm-12 col-md-6 mb-1 d-inline-flex">

                                    <a class="d-flex align-item-center mt-1 btn-outline-info rounded-pill btn-icon" href="#"
                                        title="Refresh">
                                        <em class="fas fa-redo fa-1x"></em>
                                    </a>
                                    <form action="#" class='d-flex align-items-center search' style="margin-left: 20px;"
                                        method="GET">
                                        <div>
                                            <input type="text" value="" placeholder="Search" class="form-control"
                                                name="search" required />
                                        </div>
                                        <button class="btn btn-info btn-sm btn-shadow me-1"
                                            type="submit">{{ __('vehicle_type.search') }}</button>
                                    </form>
                                </div>
                                <div class="col-sm-12 col-md-6 d-flex justify-content-end">
                                    <a href="#" data-toggle="modal" data-target="#view" class="btn btn-info btn-icon ">
                                        <em data-feather="plus"></em>New Course Category
                                    </a>
                                </div>

                            </div>
                        </div>
                        <div class="card-body table-responsive">
                            <table id="example2" class="table table-hover">
                                <thead>
                                    <tr>
                                        <th scope="col">Sno</th>
                                        <th scope="col">Category Name</th>
                                        <th scope="col">Actions</th>

                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($data as $k => $v)
                                        <tr>
                                            <td class="align-middle">{{ ++$k }}</td>
                                            <td class="align-middle">{{ $v->name }}</td>
                                            <td>
                                                {{-- <a href="{{ route('admin.course.category.edit', $v->id) }}"
                                                    class="btn btn-outline-accent btn-icon">
                                                    <i class="ci-edit"></i>
                                                </a> --}}
                                                <a href="#" data-toggle="modal" data-target="#edit{{ $v->id }}"
                                                    class="btn btn-info btn-icon ">
                                                    <em data-feather="plus" class="ci-edit"></em>
                                                </a>

                                                &nbsp;
                                                <a href="{{ route('admin.course.category.delete', $v->id) }}"
                                                    class="btn btn-outline-danger btn-icon"
                                                    onclick="return confirm('Are you sure you want to delete this item?')">
                                                    <i class="ci-trash"></i>
                                                </a>
                                            </td>

                                        </tr>
                                        @include('modal.course-category.edit')
                                        @include('modal.course.course-detail')
                                    @endforeach
                                </tbody>
                            </table>
                            <nav class="d-flex justify-content-around pt-3" aria-label="Page navigation">
                                {{ $data->links() }}
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </section>
    <!-- /.row -->
    @include('modal.course-category.create')

    <script>
        $(function() {
            $('.form-check-input').change(function() {
                var status = $(this).prop('checked') == true ? 1 : 0;
                var course_id = $(this).data('id');
                $.ajax({
                    type: "GET",
                    dataType: "json",
                    url: '/course-status',
                    data: {
                        'status': status,
                        'course_id': course_id
                    },
                    // success: function(data) {
                    //     console.log(data.success)

                    // }
                })
            })
        });
    </script>

@endsection


<!-- Optional bottom section for modals etc... -->
@section('body_bottom')
    <!-- DataTables -->
@endsection

@section('cdn')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/css/bootstrap-toggle.css"
        integrity="sha512-9tISBnhZjiw7MV4a1gbemtB9tmPcoJ7ahj8QWIc0daBCdvlKjEA48oLlo6zALYm3037tPYYulT0YQyJIJJoyMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"
        integrity="sha512-F636MAkMAhtTplahL9F6KmTfxTmYcAcjcCkyu0f0voT3N/6vzAuJ4Num55a0gEJ+hRLHhdz3vDvZpf6kqgEa5w=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@endsection